[package]
name = "notification-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = { version = "0.23", default-features = false, features = ["ring"] }
tokio = { version = "1.28.0", features = ["full"] }
lapin = "2.2.1"
mongodb = { version = "2.8", features = ["tokio-runtime"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls", "smtp-transport", "builder", "ring", "rustls-native-certs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
uuid = { version = "1.3", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

rabbitmq-rustclient = { path = "../../packages/rabbitmq-rustclient" }
metrics-rustclient = { path = "../../packages/metrics-rustclient" }
futures-lite = "2.6.1"

[[test]]
name = "email_test"
path = "test/email_test.rs"
