[package]
name = "cdc"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = { version = "0.23", default-features = false, features = ["ring"] }
tokio = { version = "1.0", features = ["full"] }
redis-rustclient = { path = "../../packages/redis-rustclient" }
pgwire-replication = "0.3"
tokio-postgres = "0.7"
native-tls = "0.2"
postgres-native-tls = "0.5"
chrono = "0.4"
bytes = "1"
dotenvy = "0.15"
serde_json = "1.0"
metrics-rustclient = { path = "../../packages/metrics-rustclient" }
