[package]
name = "game-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game-server"
path = "src/main.rs"

[dependencies]
rustls = { version = "0.23", default-features = false, features = ["ring"] }
tonic       = "0.12"
prost       = "0.13"
tokio       = { version = "1.0", features = ["full"] }
redis       = { version = "0.27", features = ["aio", "tokio-comp", "connection-manager", "streams"] }
shakmaty    = "0.27"
serde_json  = "1.0"
dotenvy     = "0.15"
metrics-rustclient = { path = "../../packages/metrics-rustclient" }

[build-dependencies]
tonic-build = "0.12"
